### PR TITLE
Disable escaping for ogns variable

### PR DESCRIPTION
**Pull request by revoltek-daniel**
disable escaping to preserve quotes in html attribute

### CODE REVIEW

**Comment by tractorcow** [comment]
This could potentially change the default escaping for the entire object; Potentially creating a severe XSS vulnerability.

What quotes do you think should not be escaped safely?

**Comment by tractorcow** [comment]
Can I suggest this


```
private static $casting = [
    'OGNS' => 'HTMLFragment',
];
```

That will not affect any other property. :)

**Comment by revoltek-daniel** [comment]
Looks like the better way to do it. I've changed it.

I'm pretty new to silverstripe so I did not recognoize that there are more than the OGNS variable.

**Review by tractorcow — APPROVED** [review]

**Comment by tractorcow** [comment]
Thanks @revoltek-daniel !

**Pull request merged**
