### PR TITLE
SS4 Upgrade.

### PR DESCRIPTION
**Pull request by bummzack**
Updated readme.
Moved to TractorCow\OpenGraph namespace.
Adhere/enforce SilverStripe coding conventions.
Added a few unit-tests (not much, but better than nothing).
Added .editorconfig, .upgrade.yml.
Added phpunit, phpcs, scrutinizer and travis configs.

### CODE REVIEW

**Comment by tractorcow** [comment]
Hi @bummzack I've merged up 3.1 into master and branched off 3, so that you can merge this into master (we'll alias as 4). can you rebase?

**Comment by bummzack** [comment]
@tractorcow Should be good to merge now. I've added the following branch alias: `"dev-master": "4.x-dev"`

**Comment by bummzack** [comment]
If you're deciding to add travis: I just saw that tests probably won't pass with the current `composer.json`, since they use `SiteTree`… so I guess you'd have to add cms as a dev-dependency… (probably better than adding it as a requirement, since this module could also be used without cms)

**Comment by bummzack** [comment]
I've fixed the `composer.json` to include cms as dev-dependency. Travis should now work if you choose to enable it.

I also fixed the PR by removing the `code` folder that was merged back in 😅

**Comment by tractorcow** [comment]
Oops sorry :)

**Pull request merged**
